### ISSUE TITLE
Allow validation to only be run on certain `req.method` types

### ISSUE THREAD

**Issue by djdembeck** [codecoolture/next-joi#16]
For example, I don't need `GET` requests to be validated, only `POST`.

**Comment by sergioalvz** [comment]
Hey @djdembeck, that's a good point. Did you try using the [`next-connect`](https://github.com/hoangvvo/next-connect) package? `next-joi` can be easily integrated with it, and it already supports this behavior:

```ts
import connect from 'next-connect';

export default connect()
  .get(validate({}), getHandlerFunction)
  .post(validate({}), postHandlerFunction);
```

**Comment by djdembeck** [comment]
Awesome, this does exactly what I needed, thanks!
