### ISSUE TITLE
Next 10 Support

### ISSUE THREAD

**Issue by ZicklePop** [codecoolture/next-joi#6]
https://github.com/codecoolture/next-joi/blob/0a5b72645c8866c712ec7f08f525d9976797ab89/package.json#L30

Hi there! Are there any plans to support Next 10?

_Edit:_ This is a peer dependency issue that comes from NPM 7 changing how peer dependencies work.

**Comment by sergioalvz** [comment]
Hi, @ZicklePop. Good point! 

I have to read about that peer dependency issue. Anyhow, it is probably better to change it to `">=9.5.1"` since I think the package is already fully compatible with Next 10.

I'll try to do it shortly. Thanks! :-)

**Comment by sergioalvz** [comment]
I just published `v2.2.1` to npm. It should be fixed now! 🚀
